export const styles = {
  button: {
    backgroundColor: '#49a25b',
    borderRadius: '18px',
    boxShadow: '0 2px 8px 0 rgb(73, 162, 91,30)',
    border: 'none',
    color: 'white',
    width: '20%',
    textAlign: 'center',
    height: '5%',
    marginBottom: '1em'
  },
  backButton: {
    backgroundColor: '#a24d0d',
    borderRadius: '18px',
    boxShadow: '0 2px 8px 0 rgb(73, 162, 91,30)',
    border: 'none',
    color: 'white',
    width: '20%',
    textAlign: 'center',
    height: '5%',
  },
  container: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  input: {
    borderRightColor: 'transparent',
    borderLeftColor: 'transparent',
    borderTopColor: '#49a25b',
    borderBottomColor: '#49a25b',
    borderBottomLefColor: '#49a25b',
    textAlign: 'center',
  },
  productName: {
    fontFamily: 'SFProText-Bold',
    fontSize: '14px',
    color: '#212121',
    textAlign: 'center',
  },
  priceText: {
    fontFamily: 'SFProText-Regular',
    fontSize: '12px',
    color: '#212121',
    textAlign: 'center',
    marginBottom: '10px',
  },
  totalContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-between',
    alignItems: 'center',
    marginBottom: '10px',
  },
  total: {
    display: 'flex',
    marginRight: '50px',
    fontFamily: 'SFProText-Bold',
    fontSize: '14px',
    color: '#212121',
    textAlign: 'center',
  },
  quantity: {
    display: 'flex',
    marginLeft: '50px',
    fontFamily: 'SFProText-Semibold',
    fontSize: '17px',
    color: '#000000',
    letterSpacing: '-0.41px',
    textAlign: ' center',
    lineHeight: '22px',
  },
  cant: {
    fontFamily: 'SFProText-Bold',
    fontSize: '12px',
    color: '#757575',
    letterSpacing: '-0.3px',
  },
  spinners: {
    display: 'flex',
    flexDirection: 'row',
    marginBottom: '60px',
  },
  addButton: {
    fontSize: '22px',
    borderColor: '#49a25b',
    textAlign: 'center',
    backgroundColor: '#49a25b',
    borderBottomRightRadius: '18px',
    borderTopRightRadius: '18px',
    color: 'white',
    fontFamily: 'SFProText-Bold',
  },
  subtractButton: {
    fontSize: '22px',
    borderColor: '#49a25b',
    textAlign: 'center',
    backgroundColor: '#49a25b',
    borderBottomLeftRadius: '18px',
    borderTopLeftRadius: '18px',
    color: 'white',
    fontFamily: 'SFProText-Bold',
  },
}
