export const styles = {
  button: {
    backgroundColor: '#49a25b',
    borderRadius: '18px',
    boxShadow: '0 2px 8px 0 rgb(73, 162, 91,30)',
    border: 'none',
    color: 'white',
    width: '20%',
    textAlign: 'center',
    height: '5%',
    marginBottom: '1em'
  },
  backButton: {
    backgroundColor: '#a24d0d',
    borderRadius: '18px',
    boxShadow: '0 2px 8px 0 rgb(73, 162, 91,30)',
    border: 'none',
    color: 'white',
    width: '20%',
    textAlign: 'center',
    height: '5%',
  },
  container: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
    height:"100vh",
  },
  textTitle: {
    width: '300px',
    height: '60px',
    textAlign: 'center',
    fontFamily: 'SFProText-Bold',
    fontSize: '4vh',
    marginTop: '30px',
    color: '#212121',
  },
  normalText: {
    fontFamily: 'SFProText-Bold',
    fontSize: '16px',
    color: '#212121',
    width: '40%',
    height: '35px',
    textAlign: 'right',
  },
  priceText: {
    fontFamily: 'SFProText-Regular',
    fontSize: '16px',
    color: '#212121',
    width: '60%',
    height: '35px',
    textAlign: 'center',
  },
  space:{
    display: 'flex',
    justifyContent: 'space-between',
    width: '220px',
    height: '30px',
    textAlign: 'center',
  },
}
