export const paths = {
  auth: `${process.env.SUBDIR}/auth`,
  location: `${process.env.SUBDIR}/auth/location`,
  home: `${process.env.SUBDIR}/`,
  quantity: `${process.env.SUBDIR}/quantity`,
  checkout: `${process.env.SUBDIR}/checkout`,
  delivery_address: `${process.env.SUBDIR}/delivery_address`,
  change_deliverer: `${process.env.SUBDIR}/change_deliverer`,
  order: `${process.env.SUBDIR}/order`,
  orders_list: `${process.env.SUBDIR}/orders_list`,
  preferences: `${process.env.SUBDIR}/preferences`,
  cart: `${process.env.SUBDIR}/cart`,
  order_details: `${process.env.SUBDIR}/order_details`,
  register: `${process.env.SUBDIR}/register`,
  login: `${process.env.SUBDIR}/login`,
}
